apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: microservices
type: Opaque
data:
  # Base64 encoded "SuperSecurePassword123!"
  password: U3VwZXJTZWN1cmVQYXNzd29yZDEyMyE=
