server:
  port: 8080

spring:
  application:
    name: order-service
  
  datasource:
    url: jdbc:postgresql://postgresql.database:5432/microservices
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  rabbitmq:
    host: rabbitmq.database
    port: 5672
    username: admin
    password: admin123

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.k8s.demo: DEBUG
    org.springframework: INFO
