apiVersion: v2
name: microservices-platform
description: Complete microservices platform for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - microservices
  - kubernetes
  - platform
maintainers:
  - name: Your Name
    email: your.email@example.com
dependencies:
  - name: postgresql
    version: 13.2.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 18.6.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: rabbitmq
    version: 12.5.0
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled